### PR TITLE
Soften cla bot language

### PR DESCRIPTION
**Pull request by maoo**

### CODE REVIEW

**Comment by maoo** [comment]
Just added "maoo" in contributors.json, see https://github.com/maoo/clabot-test/commit/4f7ded684093208fb6b1b1a19303fec8f5cf23e5

Next step is to resummon the bot, to see if the cla check passes.

**Comment by maoo** [comment]
@finos-cla-bot[bot] check

**Comment by maoo** [comment]
@finos-cla-bot-staging[bot] check

**Comment by mcleo-d** [comment]
Looks awesome @maoo 👍 💯 💯 💯  

Thanks for integrating and testing.

**Pull request closed without merging**
